-- Create the table for storing student registrations
create table students (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  student_name text not null,
  class text not null,
  parent_name text not null,
  phone text not null,
  email text not null,
  address text not null
);

-- Turn on Row Level Security
alter table students enable row level security;

-- Create a policy to allow anyone to insert valid records (Public Registration)
create policy "Enable insert for anyone" on students 
for insert 
with check (true);

-- Create a policy to allow reading only by authenticated users (conceptually for admin)
-- For this simple implementation, we might stick to anon key read if you want it strictly public for the panel
-- OR we assume the admin panel is public for now as per "simple app" requirements.
create policy "Enable read access for all users" on students
for select
using (true);
